remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Big Chillins Valheim Modpack
description: Heavily RPG Influenced Modpack for Valheim pieced together by BigChillin and DEMMERS
show_downloads: true

github:
  zip_url: https://github.com/LeDemmers/Big-Chillins-Modpack-VAL-/releases/download/1.0.1/Big_Chillins_Valheim_Modpack_1664210878241.r2z
